### PR TITLE
Validate AUTH0_DOMAIN in config

### PR DESCRIPTION
**Pull request by chrisscott**
## ✏️ Changes

 Lack of domain validation can result in less than helpful error messages that bubble up from node-auth0
 - Added a check for properly formed `AUTH0_DOMAIN` in `config.json`
 - Added test

## 🔗 References

n/a

## 🎯 Testing

Test added. Manually, test using an invalid `AUTH_DOMAIN` in `config.js`

✅ This change has unit test coverage

🚫 This change has integration test coverage

🚫 This change has been tested for performance

### CODE REVIEW

**Comment by sobil** [comment]
@chrisscott , How would this affect customers on custom domains not using `auth0.com`?

If the error messaging is particularly painful perhaps another option could be to add a preflight check to make sure the domain is an Auth0 tenant and then return the same error... 🤔  I'm sure there are probably a few ways to do that, but the first that come to mind is checking the jwks endpoint.

**Comment by chrisscott** [comment]
@sobil this wouldn't be affected by custom domains as the Management API Audience doesn't use the custom domain but the Auth0 domain.

**Comment by sobil** [comment]
> @sobil this wouldn't be affected by custom domains as the Management API Audience doesn't use the custom domain but the Auth0 domain.

When using a private appliance that's doesn't appear to be the case.  At least the working config I am looking at has an `AUTH0_DOMAIN` that does not end in `auth0.com`

**Comment by silviom** [comment]
> > @sobil this wouldn't be affected by custom domains as the Management API Audience doesn't use the custom domain but the Auth0 domain.
> 
> When using a private appliance that's doesn't appear to be the case. At least with the working config I am looking at here has an `AUTH0_DOMAIN` that does not end in `auth0.com`

That's true, not all PSaaS environments use an `.auth0.com` subdomain. For instance, some auth0 hosted customers and all customer hosted use their own domains.

**Comment by chrisscott** [comment]
Thanks for pointing this out @sobil and than you for the confirmation @silviom! I'll update the PR to reflect this.

**Comment by chrisscott** [comment]
Due to the above, I'm not sure there's much value in this PR now. I'm going to close this but happy to revive it and update it if there's interest.

**Pull request closed without merging**
