### PR TITLE
Unmark sandbox_version as readonly

### PR DESCRIPTION
**Pull request by hmd34**
### 🔧 Changes

Previously, there was a issue about sandbox_version Import. https://github.com/auth0/auth0-deploy-cli/issues/69 
So mark sandbox_version to readonly, and remove sandbox_version in export.

Now seems to have been resolved that issue. Fix so that sandbox_version is exported again.

### 📚 References
Fix: https://github.com/auth0/auth0-deploy-cli/issues/682

### 🔬 Testing

Following steps
1. Check the Node.js runtime version in tenant advanced settings
2. Export settings with a0deploy
3. Check to appears `sandbox_version` in tenant.json
4. Compare 1 and 3 step's Node version

### 📝 Checklist

- [x] All new/changed/fixed functionality is covered by tests (or N/A)
- [x] I have added documentation for all new/changed functionality (or N/A)

### CODE REVIEW

**Comment by hmd34** [comment]
E2E tests failed. I saw errors and don't know why failed. Do I need to take any action?

**Comment by Widcket** [comment]
cc @willvedd

**Comment by willvedd** [comment]
@hmd34 I haven't forgotten about this. Can confirm that support for updating `sandbox_version` was added sometime between #69 and now. I want to be particularly careful to not introduce any regressions for folks so need to double-check that including this property in payloads is compatible with all environments and permutations of the API.

**Review by willvedd — APPROVED** [review]
@hmd34 thanks for your patience here. I needed to confirm that this property was configurable and can confirm. I went ahead and updated the test recordings to get this ready for approval.

**Comment by willvedd** [comment]
Despite the CircleCI checks suggesting otherwise, all tests are indeed passing. My suspicion is that this fork's lack of environment variables being injected is interfering with the recordings. Going ahead with a merge anyway, we'll have to fix that integration later.

**Comment by hmd34** [comment]
@willvedd So sorry for delayed response and thank you for your work.

**Pull request merged**
