### PR TITLE
#813 Add functionality to enable deploy CLI client to use private key JWT 

### PR DESCRIPTION
**Pull request by aaronchilcott**
### 🔧 Changes

This change introduces support for private key JWT authentication for the deploy CLI client. Private key JWT authentication is already supported by the auth0/node-auth0 (npm auth0) library, this change only adds the requisite functionality to allow configuration values to pass through to the node-auth0 library.

### 📚 References

- GitHub issue #813 

### 🔬 Testing

Unit tests have been added which cover:
1. Failure conditions:
1.1. When neither client secret nor client private key are present
2. Success conditions
2.1 When client secret is passed through
2.2. When client private key is passed through
2.3. When client private key algorithm is passed through

### 📝 Checklist

- [x] All new/changed/fixed functionality is covered by tests
- [x] I have added documentation for all new/changed functionality

### CODE REVIEW

**Comment by aaronchilcott** [comment]
Hi all, not sure which branch to create PR in to, master seemed the likely candidate - please advise if this is incorrect.

**Comment by willvedd** [comment]
Appreciate the contribution! Authenticating this way is certainly sensible but a big enough change that we'll want to do our due diligence with this one. Please give us a little bit of time to review, adequately test and document.

**Comment by aaronchilcott** [comment]
@willvedd Can you please take a look at the failing E2E tests and decipher the output for me? I'd like to know if this is an error caused by my changes (and needs fixing) or if it's something else? It looks like something else to me, but one can never be too certain.

Thanks!

**Comment by willvedd** [comment]
@aaronchilcott I'm currently reviewing this now. Mostly looks good but I intend to add more documentation and a few minor validation changes. While I'm doing that I can re-record the tests. Appreciate you doing the heavy lifting here though.

**Comment by willvedd** [comment]
@aaronchilcott Thanks for your patience. I made several changes to your branch. Most notably is modifying the way the private key is passed. We opted to accept as a path with the `AUTH0_CLIENT_SIGNING_KEY_PATH` configuration property as opposed as to setting to an environment variable because we want to limit the exposure of the private key; if it was passed as an environment variable or in plain text as an argument, it would be visible throughout the system. 

I also took this opportunity to better document the authentication mechanisms available.

**Review by willvedd — APPROVED** [review]
Thanks for the contribution. Approving this but waiting until someone else on the team can review.

**Review by sergiught — APPROVED** [review]

**Comment by aaronchilcott** [comment]
Nice work, thanks for your help @willvedd =)

**Pull request merged**
