### PR TITLE
ESD 2006: Remove --verbose flag

### PR DESCRIPTION
**Pull request by faroceann**
## ✏️ Changes

Remove --verbose CLI option, since it provides no current functionality. 

## 🔗 References

https://auth0team.atlassian.net/browse/ESD-2006

### CODE REVIEW

**Comment by lzychowski** [comment]
@faroceann what kind of manual testing did you perform for this PR?

**Comment by faroceann** [comment]
> @faroceann what kind of manual testing did you perform for this PR?

I ran a YAML import, validated it worked and verified that the `help` dialog no longer shows `--verbose` as an option

**Comment by zxan1285** [comment]
Should we add `debug` option description instead? 
https://github.com/auth0/auth0-deploy-cli/blob/master/src/index.js#L17

**Comment by faroceann** [comment]
> Should we add `debug` option description instead?
> https://github.com/auth0/auth0-deploy-cli/blob/master/src/index.js#L17

I have updated and added the option description to `--help` and the readme.

**Pull request merged**
