### PR TITLE
Import/export support for branding with directory as source/target.

### PR DESCRIPTION
**Pull request by ean**
## ✏️ Changes

Adds support for importing and exporting branding data when using directory as target/source.

This change depends on https://github.com/auth0/auth0-deploy-cli/pull/438, I will rebase and update when it has been merged. But I wanted to get some initial feedback on this.

## 🎯 Testing

> Describe how this can be tested by reviewers. Please be specific about anything not tested and reasons why.
branding/branding.json will be written to output directory when using `directory` output format.

✅ This change has unit test coverage

### CODE REVIEW

**Comment by willvedd** [comment]
@ean Thanks for your contribution but I'm having difficulty understanding functional difference between this and #438. Can you point me to the core changes that you're proposing? AFAIK, @toddbaert 's PR already implements this, no?

**Comment by ean** [comment]
> @ean Thanks for your contribution but I'm having difficulty understanding functional difference between this and #438. Can you point me to the core changes that you're proposing? AFAIK, @toddbaert 's PR already implements this, no?

Currently, and as far as I can see with @toddbaert's PR the branding settings (logo_url, colors, etc) is not persisted to disk using running when using directory format. And there is not functionality for reading it back from disk either. The support is already in place for yaml format.

I included the changes in #438 in this PR to avoid too many conflicts to handle when that PR is merged. My changes are in the last commit on this branch.

> Further, can you advise if this is a contribution that should block the release of #438 as a feature?

No reason for this PR to block #438, this will add currently missing functionality. But getting them in on the same release will as far as I can see completely all import/export for the branding settings.

**Comment by toddbaert** [comment]
@willvedd My feature only added the templates support. As @ean notes, the branding settings being persisted was never implemented (it was indeed missing before my PR). My PR was focused only on the templates.

**Comment by willvedd** [comment]
Understood, thank you both for clarifying. I'd like to focus on getting #438 in first and then I can review this PR more thoroughly later this week.

**Comment by ean** [comment]
@willvedd do you have time to look at this soon?

**Comment by ean** [comment]
For the YAML format the values are already persisted as part of an export. It was only the directory format that was lacking it.

**Comment by toddbaert** [comment]
> For the YAML format the values are already persisted as part of an export. It was only the directory format that was lacking it.

Yep, that's what I saw as well. The YAML context simply gets the result from the auth0 handler, unlike the dir handler, no file write is needed..

**Comment by ean** [comment]
@willvedd - Based on the comments above, is this an OK standalone PR? If so I will will resolve the current conflicts and push a new version, if not I can try to incorporate anything else you feel is missing here.

**Comment by willvedd** [comment]
>Based on the comments above, is this an OK standalone PR? If so I will will resolve the current conflicts and push a new version, if not I can try to incorporate anything else you feel is missing here.

Apologies for the delay on responding. Part of me is still trying to understand why this feature only requires the change to the single branding handler, but that's more so a me problem. Secondly, we've been migrating this repo to Typescript to make contributions a bit less perilous and easier for review. It's unfortunate that you contributed in the midst of this migration because I don't think that we're interested in accepting non-typed code going forward. Again, I apologize for the lack of communication here. If you're able to take a stab at converting to TS by using the existing handlers as a guide, I'd be happy to help you push this through the pipeline; there are a couple wonky code issues here and there that I want to discuss but we can review that more closely once it's passing the typescript compiler.

Sorry for the added work here, it's actually meant to make it an easier and less erroneous contributor process going forward. If this is too much work for you, we plan on working on API parity in the coming weeks so this will be on the radar anyway and happy to push it over the finish line myself but no estimated finish time of when that would happen.

**Comment by ean** [comment]
@willvedd no worries, I fully understand the wish to move over to typescript for this.

I have rebased my changes on top over the latest master now, so please take another look.

The branding object is still untyped, but I did not see any good examples in the existing code on how you wanted the typing done.

**Comment by willvedd** [comment]
@ean I've had a bit of time to look into the directory branding support. Initially, I had a bit of trouble getting the desired functionality and tests to pass, so I created my own branch, see #505 . I'd like to acknowledge your above work, so if you're able, I invite you to review that branch and pull into this PR for eventual merging. How does that sound?

**Comment by ean** [comment]
Hi @willvedd 
I looked over your changes, and I like the overall structure. I am happy to close this PR and have your changes merged in. What is most important to me is getting the functionality in place, not being part of the commit history :)

Thanks for following up on this and getting the functionality ready.

**Pull request closed without merging**
